[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part1/ch2/ch2_pandas.ipynb)

# 판다스

## Section1. 데이터프레임과 시리즈

In [2]:
# 판다스 라이브러리 불러오기
import pandas as pd

In [194]:
# 시리즈 만들기 (문자열)
menu = pd.Series(['비빔밥', '김치찌개', '된장찌개'])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [192]:
# 시리즈 만들기(정수형)
price = pd.Series([10000, 9000, 8000])
price

0    10000
1     9000
2     8000
dtype: int64

In [195]:
# 데이터 프레임 만들기 pd.DataFrame({"컬럼명":데이터})
pd.DataFrame({
    "메뉴" : menu,
    "가격" : price
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [198]:
pd.DataFrame({
    "메뉴" : menu,    "가격" : price
})

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [6]:
# 데이터 프레임 만들기 pd.DataFrame({"컬럼명":데이터})
df = pd.DataFrame({
    "메뉴":['비빔밥', '김치찌개', '된장찌개'],
    "가격":[10000, 9000, 8000],
    "원산지":['국내산', '국내산', '국내산']
})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

In [7]:
# 시리즈 선택 (가격)
df['메뉴']

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

In [8]:
# 데이터프레임 선택 (가격)
df[['메뉴']]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [9]:
df[['메뉴', '가격']]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [10]:
# 데이터프레임 선택 (가격)
cols = ['메뉴', '가격']
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [11]:
# 데이터 프레임 type 확인
print("df          : ", type(df))
print("df['가격']   : ", type(df['가격']))
print("df[['가격']] : ", type(df[['가격']]))

df          :  <class 'pandas.core.frame.DataFrame'>
df['가격']   :  <class 'pandas.core.series.Series'>
df[['가격']] :  <class 'pandas.core.frame.DataFrame'>

## Section2. 데이터 저장 및 불러오기

In [12]:
# 데이터 준비
df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500, 5000, 5500, 5000, 4000, 5900, 5300],
    "칼로리":[10, 110, 250, 110, 20, 210, 0],
})
df

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [13]:
df.to_csv('temp.csv')

In [14]:
temp_df = pd.read_csv('temp.csv')
temp_df.head()

   Unnamed: 0     메뉴    가격  칼로리
0           0  아메리카노  4500   10
1           1   카페라떼  5000  110
2           2   카페모카  5500  250
3           3   카푸치노  5000  110
4           4  에스프레소  4000   20

In [15]:
# 데이터 불러오기
df.to_csv('cafe.csv', index=False)
df = pd.read_csv('cafe.csv')
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

## Section3. 탐색적 데이터 분석(EDA)

In [16]:
# 데이터 샘플 확인: 앞에서 부터 n개 (기본 5개)
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [17]:
# 데이터 샘플 확인: 뒤에서 부터 n개 (기본 5개)
df.tail(3)

      메뉴    가격  칼로리
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [18]:
df.sample(3)

      메뉴    가격  칼로리
3   카푸치노  5000  110
1   카페라떼  5000  110
4  에스프레소  4000   20

In [19]:
# 데이터 프레임 크기 (행, 컬럼)
df.shape

(7, 3)

In [20]:
# 컬럼 형태(type)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [21]:
# 상관관계
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

In [22]:
# 중복 값이 있는 데이터 생성
df_car = pd.DataFrame({
    "car":['Sedan','SUV','Sedan','SUV','SUV','SUV','Sedan','Sedan','Sedan','Sedan','Sedan'],
    "size":['S','M','S','S','M','M','L','S','S', 'M','S']
})
df_car.head(3)

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S

In [23]:
# 항목 종류 수
df_car.nunique()

car     2
size    3
dtype: int64

In [24]:
# 항목 종류
print(df_car['car'].unique())
print(df_car['size'].unique())

['Sedan' 'SUV']
['S' 'M' 'L']

In [25]:
# 항목별 개수
print(df_car['car'].value_counts())
print(df_car['size'].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

In [26]:
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [27]:
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [28]:
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

## Section4. 자료형 변환

In [29]:
# 데이터 준비
data = {
    "메뉴":['아메리카노', '카페라떼', '카페모카', '카푸치노', '에스프레소', '밀크티', '녹차'],
    "가격":[4500.0, 5000.0, 5500.0, 5000.0, 4000.0, 5900.0, 5300.0],
    "칼로리":['10', '110', '250', '110', '20', '210', '0'],
}
df = pd.DataFrame(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [30]:
# 자료형 변환 / astype /  object -> int
df['가격'] = df['가격'].astype('int')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [31]:
df['칼로리'] = df['칼로리'].astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

## Section5. 새로운 컬럼 추가

In [32]:
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [33]:
# 새로운 컬럼 추가 (값은 0)
df['new'] = 0
df.head(2)

      메뉴    가격  칼로리  new
0  아메리카노  4500   10    0
1   카페라떼  5000  110    0

In [34]:
# 할인가 컬럼 추가
discount = 0.2
df['할인가'] = df['가격'] * (1-discount)
df.head(2)

      메뉴    가격  칼로리  new     할인가
0  아메리카노  4500   10    0  3600.0
1   카페라떼  5000  110    0  4000.0

## Section6. 데이터 삭제 (컬럼, 행)

In [35]:
df = pd.read_csv('cafe.csv')
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250

### 행 삭제

In [36]:
# 행 삭제
df.drop(1, axis=0, inplace=True)
df.head(3)

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110

### 컬럼 삭제

In [37]:
# 데이터 삭제
# axis=0:행방향, axis=1:열방향(컬럼)
df = df.drop('칼로리', axis=1)
df.head(3)

      메뉴    가격
0  아메리카노  4500
2   카페모카  5500
3   카푸치노  5000

## Section7. 인덱싱/슬라이싱(loc)
- 인덱스 명
- 인덱스 명(범위), 컬럼 명(범위)

In [38]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [39]:
# 인덱싱 (행 전체)
# 아메리카노
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [40]:
# 카페라떼 가격
df.loc[1, "가격"]

np.int64(5000)

In [41]:
# 슬라이싱 (컬럼 전체)
# 가격
df.loc[:, "가격"]

0    4500
1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [42]:
# 슬라이싱
df.loc[2, '메뉴':'칼로리']

메뉴     카페모카
가격     5500
칼로리     250
Name: 2, dtype: object

In [43]:
# 슬라이싱
# 카페모카 메뉴와 칼로리
df.loc[2, ['메뉴', '칼로리']]

메뉴     카페모카
칼로리     250
Name: 2, dtype: object

In [44]:
# 슬라이싱
df.loc[1:3, '메뉴':'가격']

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500
3  카푸치노  5000

## Section8. 인덱싱/슬라이싱(iloc)
- 인덱스 번호
- 인덱스 번호(범위), 컬럼 번호(범위)

In [45]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.drop(0, axis=0, inplace=True) # 첫번째 행 삭제
df.head(2)

     메뉴    가격  칼로리
1  카페라떼  5000  110
2  카페모카  5500  250

In [46]:
# 인덱싱 (행 전체)
# 카페라떼
df.iloc[0]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [47]:
# 슬라이싱 (컬럼 전체)
# 가격
df.iloc[:, 1]

1    5000
2    5500
3    5000
4    4000
5    5900
6    5300
Name: 가격, dtype: int64

In [48]:
# 슬라이싱
# 카페모카 메뉴와 가격
df.iloc[2, 0:2]

메뉴    카푸치노
가격    5000
Name: 3, dtype: object

In [49]:
# 슬라이싱 (카페라떼와 카페모카의 전체 데이터)
df.iloc[1:3]

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

In [50]:
df.loc[2:3,'메뉴':'칼로리']

     메뉴    가격  칼로리
2  카페모카  5500  250
3  카푸치노  5000  110

## Section9. 데이터 추가/변경

In [51]:
# 데이터 불러오기
df = pd.read_csv('cafe.csv')
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [52]:
# 결측값으로 추가, 원두 컬럼을 만들고 결측값(NaN)으로 대입
import numpy as np
df['원산지'] = np.nan
df.head(4)

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN
2   카페모카  5500  250  NaN
3   카푸치노  5000  110  NaN

In [53]:
# 아메리카노의 원두는 '콜롬비아' 데이터 추가
df.loc[0, "원산지"] = '콜롬비아'
df.loc[2:3, "원산지"] = '과테말라'
df.head(4)

/tmp/ipython-input-1959328268.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0, "원산지"] = '콜롬비아'

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라

In [54]:
# 리스트 형태로 데이터(행) 추가
df.loc['시즌'] = ['크리스마스라떼', 6000, 300, '한국']
df.tail(3)

         메뉴    가격  칼로리  원산지
5       밀크티  5900  210  NaN
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국

In [55]:
# 딕셔너리 형태로 데이터(행) 추가
df.loc[7] = {'메뉴':'딴짓커피', '가격':2000, '칼로리':20}
df.tail(3)

         메뉴    가격  칼로리  원산지
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국
7      딴짓커피  2000   20  NaN

In [56]:
df.drop("시즌", axis=0, inplace=True)
df.to_csv('cafe2.csv', index=False)

## Section10. 정렬

In [57]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [58]:
# 인덱스 기준 (기본값 ascending=True)
df.sort_index(ascending=False)

      메뉴    가격  칼로리   원산지
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN
5    밀크티  5900  210   NaN
4  에스프레소  4000   20   NaN
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
0  아메리카노  4500   10  콜롬비아

In [59]:
# 값 기준 (기본값 ascending=True)
# 메뉴 기준 정렬
df.sort_values('메뉴',ascending=False)

      메뉴    가격  칼로리   원산지
3   카푸치노  5000  110  과테말라
2   카페모카  5500  250  과테말라
1   카페라떼  5000  110   NaN
4  에스프레소  4000   20   NaN
0  아메리카노  4500   10  콜롬비아
5    밀크티  5900  210   NaN
7   딴짓커피  2000   20   NaN
6     녹차  5300    0   NaN

In [60]:
# 가격과 메뉴 기준 정렬
df.sort_values(['가격', '메뉴'],ascending=[False, True], inplace=True)
df

      메뉴    가격  칼로리   원산지
5    밀크티  5900  210   NaN
2   카페모카  5500  250  과테말라
6     녹차  5300    0   NaN
1   카페라떼  5000  110   NaN
3   카푸치노  5000  110  과테말라
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

In [61]:
# 인덱스 새로 만들기 drop=True
df.reset_index(drop=True)

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레소  4000   20   NaN
7   딴짓커피  2000   20   NaN

## Section11. 필터링

In [62]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [63]:
df['칼로리'] < 50

0     True
1    False
2    False
3    False
4     True
5    False
6     True
7     True
Name: 칼로리, dtype: bool

In [64]:
# 1개 조건
cond = df['칼로리'] < 50
df[cond]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [65]:
# 1개 조건
df[df['칼로리'] < 50]

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
4  에스프레소  4000   20   NaN
6     녹차  5300    0   NaN
7   딴짓커피  2000   20   NaN

In [66]:
cond = df['칼로리'] < 50
df[~cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [67]:
# 2개 이상 일때 (AND)
cond1 = df['가격'] >= 5000
cond2 = df['칼로리'] > 100
df[cond1 & cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN

In [68]:
# 2개 이상 일때 (OR)
df[cond1 | cond2]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라
5   밀크티  5900  210   NaN
6    녹차  5300    0   NaN

In [69]:
# 문자열 1개 조건
# 원두 == 콜롬비아
cond = (df['원산지'] == "과테말라")
df[cond]

     메뉴    가격  칼로리   원산지
2  카페모카  5500  250  과테말라
3  카푸치노  5000  110  과테말라

In [70]:
# 문자열과 숫자 조건 (AND)
cond1 = df['원산지'] == "과테말라"
cond2 = df['가격'] <= 5000
df[cond1 & cond2]

     메뉴    가격  칼로리   원산지
3  카푸치노  5000  110  과테말라

In [71]:
df['메뉴'].isin(['녹차'])

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: 메뉴, dtype: bool

In [72]:
cond = df['메뉴'].isin(['녹차'])
df[cond]

   메뉴    가격  칼로리  원산지
6  녹차  5300    0  NaN

In [73]:
box = ['녹차', '카푸치노', '카페라떼']
cond = df['메뉴'].isin(box)
df[cond]

     메뉴    가격  칼로리   원산지
1  카페라떼  5000  110   NaN
3  카푸치노  5000  110  과테말라
6    녹차  5300    0   NaN

## Section12. 결측치 처리

In [74]:
# 데이터 불러오기
df = pd.read_csv('cafe2.csv')
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [75]:
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [76]:
# 컬럼별 결측치 확인
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [77]:
# 컬럼별 결측치 확인
df.isna().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [78]:
# 결측값 채우기 (FutureWarning은 무시해도 된다.)
df['원산지'].fillna('코스타리카', inplace=True)
df

/tmp/ipython-input-322007724.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['원산지'].fillna('코스타리카', inplace=True)

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [79]:
df.to_csv("cafe3.csv", index=False)

## Section13. 값 변경

In [80]:
# 데이터 확인
pd.read_csv("cafe3.csv")
df.head(3)

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라

In [81]:
# 문자 변경 : 아메리카노 -> 룽고, 녹차 -> 그린티
df.replace('아메리카노', '룽고', inplace=True)
df.replace('녹차','그린티', inplace=True)
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [82]:
change = {'룽고':'아메리카노', '그린티':'녹차'}
df.replace(change, inplace=True)
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓커피  2000   20  코스타리카

In [83]:
# loc로 값 변경하기
df.loc[6, '원산지'] = '대한민국'
df.tail(3)

     메뉴    가격  칼로리    원산지
5   밀크티  5900  210  코스타리카
6    녹차  5300    0   대한민국
7  딴짓커피  2000   20  코스타리카

In [84]:
# 이벤트가 전체 1000으로 변경
df.loc[1:2, '이벤트가'] = 1000
df.head()

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN

In [85]:
df.to_csv("cafe4.csv", index=False)

In [86]:
# map() 함수
import pandas as pd
df = pd.DataFrame({'만족도': ['만족', '보통' ,'불만', '보통', '만족']})

mapping = {'만족': 3, '보통': 2, '불만': 1}
df['만족도_숫자'] = df['만족도'].map(mapping)
df

  만족도  만족도_숫자
0  만족       3
1  보통       2
2  불만       1
3  보통       2
4  만족       3

## Section14. 문자열

In [87]:
import pandas as pd
df = pd.DataFrame({'A': ['데이터 분석', '기본 학습서', '퇴근 후 열공'],
                   'B': [10, 20, 30],
                   'C': ['ab cd', 'AB CD', 'ab cd ']
                   })
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [88]:
df['A'] = df['A'].replace('분석', '시각화')
df

         A   B       C
0   데이터 분석  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [89]:
df['A'] = df['A'].str.replace('분석', '시각화')
df

         A   B       C
0  데이터 시각화  10   ab cd
1   기본 학습서  20   AB CD
2  퇴근 후 열공  30  ab cd

In [90]:
df['B'] = df['B'].replace(10, 100)
df

         A    B       C
0  데이터 시각화  100   ab cd
1   기본 학습서   20   AB CD
2  퇴근 후 열공   30  ab cd

In [91]:
# 에러
# df['B'] = df['B'].str.replace(20, 200)
# print(df)

In [92]:
# 문자열 분리
df['A'].str.split()

0     [데이터, 시각화]
1      [기본, 학습서]
2    [퇴근, 후, 열공]
Name: A, dtype: object

In [93]:
df['A'].str.split()[0]

['데이터', '시각화']

In [94]:
df['D'] = df['A'].str.split().str[0]
df

         A    B       C    D
0  데이터 시각화  100   ab cd  데이터
1   기본 학습서   20   AB CD   기본
2  퇴근 후 열공   30  ab cd    퇴근

In [95]:
# 문자 검색
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [96]:
df['기본포함유무'] = df['A'].str.contains('기본')
df

         A    B       C    D  기본포함유무
0  데이터 시각화  100   ab cd  데이터   False
1   기본 학습서   20   AB CD   기본    True
2  퇴근 후 열공   30  ab cd    퇴근   False

In [97]:
menu = pd.Series(['맛난버거 세트', '매운 치킨버거', '더블 치즈버거'])
menu.isin(['맛난버거 세트', '더블 치즈버거'])

0     True
1    False
2     True
dtype: bool

In [98]:
menu.str.contains('세트')

0     True
1    False
2    False
dtype: bool

In [99]:
df['문자길이'] = df['A'].str.len()
df

         A    B       C    D  기본포함유무  문자길이
0  데이터 시각화  100   ab cd  데이터   False     7
1   기본 학습서   20   AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd    퇴근   False     7

In [100]:
'AB cd' == 'ab CD'

False

In [101]:
df['C'] = df['C'].str.lower()
df['C']

0     ab cd
1     ab cd
2    ab cd
Name: C, dtype: object

In [102]:
df['C'] = df['C'].str.upper()
df['C']

0     AB CD
1     AB CD
2    AB CD
Name: C, dtype: object

In [103]:
df['C'] == 'AB CD'

0     True
1     True
2    False
Name: C, dtype: bool

In [104]:
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(" ","")
df['C']

0    abcd
1    abcd
2    abcd
Name: C, dtype: object

In [105]:
df['C'].str[1:3]

0    bc
1    bc
2    bc
Name: C, dtype: object

In [106]:
df['C'][1:3]

1    abcd
2    abcd
Name: C, dtype: object

## Section15. 내장함수
- 데이터 핸들링을 위한 판다스 기초1(EDA) 부분에서 일부 내장함수를 학습했고, 그외 함수에 대해 살펴봄

In [107]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [108]:
print(len(df))
print(df.shape[0])

8
8

In [109]:
cond = df['가격'] > 5000

#sum으로 조건에 맞는 개수 구하기
print(sum(cond))

#len으로 조건에 맞는 개수 구하기
print(len(df[cond]))

3
3

In [110]:
df.sum(numeric_only=True)

가격      37200.0
칼로리       730.0
이벤트가     2000.0
dtype: float64

In [111]:
df.sum(axis=1, numeric_only=True)

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    2020.0
dtype: float64

In [112]:
print("최대값: ",df['가격'].max())
print("최소값: ",df['가격'].min())
print("평균값: ",df['가격'].mean())
print("중앙값: ",df['가격'].median())
print("합계: ",df['가격'].sum())
print("표준편차: ",df['가격'].std())
print("분산: ",df['가격'].var())

최대값:  5900
최소값:  2000
평균값:  4650.0
중앙값:  5000.0
합계:  37200
표준편차:  1220.070255588353
분산:  1488571.4285714286

In [113]:
# 분위수
print("분위수 25% 값", df['가격'].quantile(.25))
print("분위수 75% 값", df['가격'].quantile(.75))

분위수 25% 값 4375.0
분위수 75% 값 5350.0

In [114]:
# 하위 25% 데이터
cond = df['가격'].quantile(.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
4  에스프레소  4000   20  코스타리카   NaN
7   딴짓커피  2000   20  코스타리카   NaN

In [115]:
# 상위 25% 데이터
cond = df['가격'].quantile(.75) < df['가격']
df[cond]

     메뉴    가격  칼로리    원산지    이벤트가
2  카페모카  5500  250   과테말라  1000.0
5   밀크티  5900  210  코스타리카     NaN

In [116]:
# 최빈값 구하기
df['원산지'].mode()[0]

'코스타리카'

In [117]:
df['가격'].idxmax()

5

In [118]:
max_ind = df['가격'].idxmax()
df.loc[max_ind]

메뉴        밀크티
가격       5900
칼로리       210
원산지     코스타리카
이벤트가      NaN
Name: 5, dtype: object

In [119]:
# df.loc[max_ind, '메뉴'] # 추천 방법
df.loc[max_ind]['메뉴'] # 다른 방법

'밀크티'

In [120]:
df.nlargest(3, '가격')

     메뉴    가격  칼로리    원산지    이벤트가
5   밀크티  5900  210  코스타리카     NaN
2  카페모카  5500  250   과테말라  1000.0
6    녹차  5300    0   대한민국     NaN

In [121]:
df.nsmallest(2, '가격')

      메뉴    가격  칼로리    원산지  이벤트가
7   딴짓커피  2000   20  코스타리카   NaN
4  에스프레소  4000   20  코스타리카   NaN

In [122]:
# apply 적용해서 새로운 컬럼 생성 (칼로리 컬럼 활용)
def cal(x):
    if x >= 100:
        return "No"
    else:
        return "Yes"

df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

      메뉴    가격  칼로리    원산지    이벤트가 먹어도 될까요
0  아메리카노  4500   10   콜롬비아     NaN     Yes
1   카페라떼  5000  110  코스타리카  1000.0      No
2   카페모카  5500  250   과테말라  1000.0      No
3   카푸치노  5000  110   과테말라     NaN      No
4  에스프레소  4000   20  코스타리카     NaN     Yes
5    밀크티  5900  210  코스타리카     NaN      No
6     녹차  5300    0   대한민국     NaN     Yes
7   딴짓커피  2000   20  코스타리카     NaN     Yes

In [123]:
import pandas as pd
df = pd.DataFrame({'Name': {0: '쿼카', 1: '알파카', 2: '시바견'},
                   '수학': {0: 90, 1: 93, 2: 85},
                   '영어': {0: 92, 1: 84, 2: 86},
                   '국어': {0: 91, 1: 94, 2: 83},})

df

  Name  수학  영어  국어
0   쿼카  90  92  91
1  알파카  93  84  94
2  시바견  85  86  83

In [124]:
pd.melt(df, id_vars=['Name'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [125]:
pd.melt(df, id_vars=['Name'], value_vars=['수학', '영어'])

  Name variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86

In [126]:
pd.melt(df, id_vars=['Name'], var_name='과목', value_name='점수')

  Name  과목  점수
0   쿼카  수학  90
1  알파카  수학  93
2  시바견  수학  85
3   쿼카  영어  92
4  알파카  영어  84
5  시바견  영어  86
6   쿼카  국어  91
7  알파카  국어  94
8  시바견  국어  83

In [127]:
import pandas as pd

df = pd.DataFrame({
    "반": ["A반", "A반", "B반"],  # 반 정보 추가
    "이름": ["쿼카", "알파카", "시바견"],
    "수학": [90, 93, 85],
    "영어": [92, 84, 86],
    "국어": [91, 94, 83]
})
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  86  83

In [128]:
pd.melt(df, id_vars=["반", "이름"], var_name="과목", value_name="점수")

    반   이름  과목  점수
0  A반   쿼카  수학  90
1  A반  알파카  수학  93
2  B반  시바견  수학  85
3  A반   쿼카  영어  92
4  A반  알파카  영어  84
5  B반  시바견  영어  86
6  A반   쿼카  국어  91
7  A반  알파카  국어  94
8  B반  시바견  국어  83

## Section16. 그룹핑

In [129]:
df = pd.read_csv("cafe4.csv")
df.head(2)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0

In [130]:
# 원두 기준, 평균
df.groupby(['원산지']).mean(numeric_only=True)

           가격    칼로리    이벤트가
원산지
과테말라   5250.0  180.0  1000.0
대한민국   5300.0    0.0     NaN
코스타리카  4225.0   90.0  1000.0
콜롬비아   4500.0   10.0     NaN

In [131]:
# 원두와 할인율 기준, 평균
df.groupby(['원산지', '칼로리']).mean(numeric_only=True)

               가격    이벤트가
원산지   칼로리
과테말라  110  5000.0     NaN
      250  5500.0  1000.0
대한민국  0    5300.0     NaN
코스타리카 20   3000.0     NaN
      110  5000.0  1000.0
      210  5900.0     NaN
콜롬비아  10   4500.0     NaN

In [132]:
df.groupby(['원산지', '메뉴']).agg(['mean', 'sum'])

                 가격          칼로리         이벤트가
               mean   sum   mean  sum    mean     sum
원산지   메뉴
과테말라  카페모카   5500.0  5500  250.0  250  1000.0  1000.0
      카푸치노   5000.0  5000  110.0  110     NaN     0.0
대한민국  녹차     5300.0  5300    0.0    0     NaN     0.0
코스타리카 딴짓커피   2000.0  2000   20.0   20     NaN     0.0
      밀크티    5900.0  5900  210.0  210     NaN     0.0
      에스프레소  4000.0  4000   20.0   20     NaN     0.0
      카페라떼   5000.0  5000  110.0  110  1000.0  1000.0
콜롬비아  아메리카노  4500.0  4500   10.0   10     NaN     0.0

In [133]:
# 1개 인덱스 형태로 리셋
df.groupby(['원산지', '칼로리']).mean(numeric_only=True).reset_index()

     원산지  칼로리      가격    이벤트가
0   과테말라  110  5000.0     NaN
1   과테말라  250  5500.0  1000.0
2   대한민국    0  5300.0     NaN
3  코스타리카   20  3000.0     NaN
4  코스타리카  110  5000.0  1000.0
5  코스타리카  210  5900.0     NaN
6   콜롬비아   10  4500.0     NaN

In [134]:
# transform
import pandas as pd

# 데이터 생성 (일부 결측값 포함)
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [135]:
price = df.groupby('과일')['가격'].transform("mean")
price

0    1500.0
1    2150.0
2    1500.0
3    2150.0
4    1500.0
5    2150.0
6    1500.0
7    2150.0
Name: 가격, dtype: float64

In [136]:
df['가격'] = df['가격'].fillna(price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [137]:
df = pd.DataFrame({
    '과일': ['딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리', '딸기', '블루베리'],
    '등급': ['B', 'B', 'A', 'A', 'A', 'A', 'B', 'B'],  # 새로운 그룹 추가
    '가격': [1000, None, 1500, None, 2000, 2500, None, 1800]  # 결측값 포함
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [138]:
price = df.groupby(['과일', '등급'])['가격'].transform("mean")
price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [139]:
df['가격'] = df['가격'].fillna(price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

In [140]:
# unstack
import pandas as pd

coffee_data = {
    '커피종류': ['아메리카노', '아메리카노', '아메리카노', '라떼', '라떼', '라떼'],
    '컵크기': ['Small', 'Medium', 'Large', 'Small', 'Medium', 'Large'],
    '판매량': [120, 150, 200, 100, 130, 180]
}
df = pd.DataFrame(coffee_data)
df

    커피종류     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [141]:
# groupby 적용
grouped = df.groupby(['커피종류', '컵크기'])['판매량'].sum()
grouped

커피종류   컵크기
라떼     Large     180
       Medium    130
       Small     100
아메리카노  Large     200
       Medium    150
       Small     120
Name: 판매량, dtype: int64

In [142]:
# 컵크기를 컬럼으로 변환
grouped.unstack()

컵크기    Large  Medium  Small
커피종류
라떼       180     130    100
아메리카노    200     150    120

In [143]:
# 커피종류를 컬럼으로 변환
grouped.unstack(level=0)

커피종류     라떼  아메리카노
컵크기
Large   180    200
Medium  130    150
Small   100    120

In [144]:
# 두 번의 unstack 적용
grouped.unstack().unstack()

컵크기     커피종류
Large   라떼       180
        아메리카노    200
Medium  라떼       130
        아메리카노    150
Small   라떼       100
        아메리카노    120
dtype: int64

## Section17. 시계열 데이터 (Datetime)

In [145]:
import pandas as pd
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
    'DateTime1': ['24-02-17 13:45:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
    'DateTime2': ['2024-02-17 13-45-30', '2024-02-18 14-55-45', '2024-02-19 15-30-15', '2024-02-20 16-10-50'],
    'DateTime3': ['02/17/2024 01:45:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
    'DateTime4': ['17 Feb 2024 13:45:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50']
}

df = pd.DataFrame(data)
df.to_csv("date_data.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:45:30,2024-02-17 13-45-30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14-55-45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15-30-15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16-10-50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [147]:
df = pd.read_csv("date_data.csv")
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'])
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
df

/tmp/ipython-input-2722885956.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])
/tmp/ipython-input-2722885956.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime1'] = pd.to_datetime(df['DateTime1'])
/tmp/ipython-input-2722885956.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime3'] = pd.to_datetime(df['DateTime3'])

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2017-02-24 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2018-02-24 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2019-02-24 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2020-02-24 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50

In [148]:
df = pd.read_csv("date_data.csv")
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'], format='%y/%m/%d')
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format='%y-%m-%d %H:%M:%S')
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df[['Date2', 'Date3', 'DateTime1', 'DateTime2']]

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [149]:
cols = ['Date2', 'Date3', 'DateTime1', 'DateTime2']
df[cols]

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      datetime64[ns]
 2   Date3      4 non-null      datetime64[ns]
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      datetime64[ns]
 6   DateTime2  4 non-null      datetime64[ns]
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: datetime64[ns](4), object(5)
memory usage: 420.0+ bytes

In [151]:
df['year'] = df['DateTime1'].dt.year
df['month'] = df['DateTime1'].dt.month
df['day'] = df['DateTime1'].dt.day
df['hour'] = df['DateTime1'].dt.hour
df['minute'] = df['DateTime1'].dt.minute
df['second'] = df['DateTime1'].dt.second
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4,year,month,day,hour,minute,second
0,2024-02-17,2024-02-17,2024-02-17,02/17/2024,17-Feb-2024,2024-02-17 13:45:30,2024-02-17 13:45:30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30,2024,2,17,13,45,30
1,2024-02-18,2024-02-18,2024-02-18,02/18/2024,18-Feb-2024,2024-02-18 14:55:45,2024-02-18 14:55:45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45,2024,2,18,14,55,45
2,2024-02-19,2024-02-19,2024-02-19,02/19/2024,19-Feb-2024,2024-02-19 15:30:15,2024-02-19 15:30:15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15,2024,2,19,15,30,15
3,2024-02-20,2024-02-20,2024-02-20,02/20/2024,20-Feb-2024,2024-02-20 16:10:50,2024-02-20 16:10:50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50,2024,2,20,16,10,50

In [152]:
df['DateTime1'].dt.dayofweek

0    5
1    6
2    0
3    1
Name: DateTime1, dtype: int32

In [153]:
print(df['DateTime1'].dt.to_period('Y'))
print(df['DateTime1'].dt.to_period('Q'))
print(df['DateTime1'].dt.to_period('M'))
print(df['DateTime1'].dt.to_period('D'))
print(df['DateTime1'].dt.to_period('H'))

0    2024
1    2024
2    2024
3    2024
Name: DateTime1, dtype: period[Y-DEC]
0    2024Q1
1    2024Q1
2    2024Q1
3    2024Q1
Name: DateTime1, dtype: period[Q-DEC]
0    2024-02
1    2024-02
2    2024-02
3    2024-02
Name: DateTime1, dtype: period[M]
0    2024-02-17
1    2024-02-18
2    2024-02-19
3    2024-02-20
Name: DateTime1, dtype: period[D]
0    2024-02-17 13:00
1    2024-02-18 14:00
2    2024-02-19 15:00
3    2024-02-20 16:00
Name: DateTime1, dtype: period[h]

/tmp/ipython-input-2095775091.py:5: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  print(df['DateTime1'].dt.to_period('H'))

## Section18. 시계열 데이터 (Timedelta)

In [154]:
df = pd.read_csv("date_data.csv", usecols=['DateTime4'], parse_dates=['DateTime4'])
df

            DateTime4
0 2024-02-17 13:45:30
1 2024-02-18 14:55:45
2 2024-02-19 15:30:15
3 2024-02-20 16:10:50

In [155]:
day = pd.Timedelta(days=99)
df['100day'] = df['DateTime4'] + day
df

            DateTime4              100day
0 2024-02-17 13:45:30 2024-05-26 13:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50

In [156]:
hour = pd.Timedelta(hours=100)
df['100hour'] = df['DateTime4'] + hour
df

            DateTime4              100day             100hour
0 2024-02-17 13:45:30 2024-05-26 13:45:30 2024-02-21 17:45:30
1 2024-02-18 14:55:45 2024-05-27 14:55:45 2024-02-22 18:55:45
2 2024-02-19 15:30:15 2024-05-28 15:30:15 2024-02-23 19:30:15
3 2024-02-20 16:10:50 2024-05-29 16:10:50 2024-02-24 20:10:50

In [157]:
difference = pd.Timedelta(weeks=7, days=7, hours=7, minutes=7, seconds=7)
df['difference'] = df['DateTime4'] - difference
df

,DateTime4,100day,100hour,difference
0,2024-02-17 13:45:30,2024-05-26 13:45:30,2024-02-21 17:45:30,2023-12-23 06:38:23
1,2024-02-18 14:55:45,2024-05-27 14:55:45,2024-02-22 18:55:45,2023-12-24 07:48:38
2,2024-02-19 15:30:15,2024-05-28 15:30:15,2024-02-23 19:30:15,2023-12-25 08:23:08
3,2024-02-20 16:10:50,2024-05-29 16:10:50,2024-02-24 20:10:50,2023-12-26 09:03:43

In [158]:
diff = df['100hour'] - df['difference']
diff

0   60 days 11:07:07
1   60 days 11:07:07
2   60 days 11:07:07
3   60 days 11:07:07
dtype: timedelta64[ns]

In [159]:
print(diff.dt.total_seconds()) # 초
print(diff.dt.total_seconds()/60) # 분
print(diff.dt.total_seconds()/60/60) # 시간
print(diff.dt.total_seconds()/60/60/24) # 일

0    5224027.0
1    5224027.0
2    5224027.0
3    5224027.0
dtype: float64
0    87067.116667
1    87067.116667
2    87067.116667
3    87067.116667
dtype: float64
0    1451.118611
1    1451.118611
2    1451.118611
3    1451.118611
dtype: float64
0    60.463275
1    60.463275
2    60.463275
3    60.463275
dtype: float64

In [160]:
print(diff.dt.days)
print(diff.dt.seconds)

0    60
1    60
2    60
3    60
dtype: int64
0    40027
1    40027
2    40027
3    40027
dtype: int32

In [161]:
min = 5.41
print(int(min), "분")
print(0.41*60, "초")

5 분
24.599999999999998 초

In [162]:
print(round(diff.dt.total_seconds()/60))

0    87067.0
1    87067.0
2    87067.0
3    87067.0
dtype: float64

## Section19. 데이터 합치기

In [163]:
import pandas as pd

# 에피타이저 메뉴
appetizer = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Bread'],
    'Price': [5000, 3000, 2000]
})

# 메인 메뉴
main = pd.DataFrame({
    'Menu': ['Steak', 'Pasta', 'Chicken'],
    'Price': [15000, 12000, 10000]
})
print(appetizer)
print(main)

    Menu  Price
0  Salad   5000
1   Soup   3000
2  Bread   2000
      Menu  Price
0    Steak  15000
1    Pasta  12000
2  Chicken  10000

In [164]:
# 두 메뉴를 수직으로 연결
full_menu = pd.concat([appetizer, main], ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [165]:
# 두 메뉴를 좌우로 연결
full_menu = pd.concat([appetizer, main], axis=1)
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

In [166]:
# 메뉴와 가격
price = pd.DataFrame({
    'Menu': ['Salad', 'Soup', 'Steak', 'Pasta'],
    'Price': [5000, 3000, 15000, 12000]
})

# 메뉴와 칼로리
cal = pd.DataFrame({
    'Menu': ['Soup', 'Steak', 'Pasta','Salad'],
    'Calories': [100, 500, 400, 150]
})

# 두 데이터프레임을 'Menu'를 기준으로 병합
menu_info = pd.merge(price, cal, on='Menu')
menu_info

    Menu  Price  Calories
0  Salad   5000       150
1   Soup   3000       100
2  Steak  15000       500
3  Pasta  12000       400

## Section20.피벗테이블

In [167]:
import pandas as pd

# 직원별 부서 및 급여 정보
data = {
    '이름': ['서아', '다인', '채아', '예담', '종현', '태헌'],
    '부서': ['개발', '기획', '개발', '기획', '개발', '기획'],
    '급여': [3000, 3200, 3100, 3300, 2900, 3100]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서별 평균 급여 계산
pt = df.pivot_table(index='부서', values='급여', aggfunc='mean')
print("\n[부서별 평균 급여]") #\n은 줄 바꿈(새로운 줄 시작)
print(pt)

[원본 데이터]
   이름  부서    급여
0  서아  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

[부서별 평균 급여]
        급여
부서
개발  3000.0
기획  3200.0

In [168]:
# 부서와 직급별 급여 정보
data = {
    '부서': ['개발', '기획', '기획', '기획', '개발', '개발'],
    '직급': ['대리', '과장', '대리', '과장', '대리', '과장'],
    '급여': [3000, 4000, 3200, 4200, 3500, 4500]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 직급별 급여 합계 계산
pt = df.pivot_table(index='부서', columns='직급', values='급여', aggfunc='sum')
print("\n[부서 및 직급별 급여 합계]")
print(pt)

[원본 데이터]
   부서  직급    급여
0  개발  대리  3000
1  기획  과장  4000
2  기획  대리  3200
3  기획  과장  4200
4  개발  대리  3500
5  개발  과장  4500

[부서 및 직급별 급여 합계]
직급    과장    대리
부서
개발  4500  6500
기획  8200  3200

In [169]:
# 부서와 성별, 근속연수 정보
data = {
    '부서': ['개발', '기획', '기획', '기획', '개발', '개발'],
    '성별': ['남', '여', '남', '여', '남', '여'],
    '근속연수': [3, 5, 4, 6, 7, 8]
}
df = pd.DataFrame(data)
print("[원본 데이터]")
print(df)

# 부서 및 성별 평균 근속연수 계산
pt = df.pivot_table(index='부서', columns='성별', values='근속연수', aggfunc='mean')
print("\n[부서 및 성별 평균 근속연수]")
print(pt)

[원본 데이터]
   부서 성별  근속연수
0  개발  남     3
1  기획  여     5
2  기획  남     4
3  기획  여     6
4  개발  남     7
5  개발  여     8

[부서 및 성별 평균 근속연수]
성별    남    여
부서
개발  5.0  8.0
기획  4.0  5.5

In [170]:
# 다양한 집계를 위한 데이터셋
import pandas as pd

df = pd.DataFrame({
    "구분": ["전자", "전자", "전자", "전자", "전자", "가전", "가전", "가전", "가전"],
    "유형": ["일반", "일반", "일반", "특수", "특수", "일반", "일반", "특수", "특수"],
    "크기": ["소형", "대형", "대형", "소형", "소형", "대형", "소형", "소형", "대형"],
    "수량": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    "금액": [2, 4, 5, 5, 6, 6, 8, 9, 9]
})
print(df)

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [171]:
# 단일 값에 대해 집계
pt = pd.pivot_table(
    df,
    values='수량',
    index=['구분', '유형'],
    columns=['크기'],
    aggfunc="sum"
)
pt

크기      대형   소형
구분 유형
가전 일반  4.0  5.0
   특수  7.0  6.0
전자 일반  4.0  1.0
   특수  NaN  6.0

In [172]:
# 단일 값에 대해 집계 (누락 값 0 처리)
pt = pd.pivot_table(
    df,
    values='수량',
    index=['구분', '유형'],
    columns=['크기'],
    aggfunc="sum",
    fill_value=0
)
pt

크기     대형  소형
구분 유형
가전 일반   4   5
   특수   7   6
전자 일반   4   1
   특수   0   6

In [173]:
# 여러 열에 대해 각기 다른 집계 함수 적용
pt = pd.pivot_table(
    df,
    values=['수량', '금액'],
    index=['구분', '크기'],
    aggfunc={'수량': "mean", '금액': "mean"}
)
pt

             금액        수량
구분 크기
가전 대형  7.500000  5.500000
   소형  8.500000  5.500000
전자 대형  4.500000  2.000000
   소형  4.333333  2.333333

In [174]:
# 하나의 열에 대해 여러 집계 함수를 동시에 적용
pt = pd.pivot_table(
    df,
    values=['수량', '금액'],
    index=['구분', '크기'],
    aggfunc={'수량': "mean", '금액': ["min", "max", "mean"]}
)
pt

       금액                      수량
      max      mean min      mean
구분 크기
가전 대형   9  7.500000   6  5.500000
   소형   9  8.500000   8  5.500000
전자 대형   5  4.500000   4  2.000000
   소형   6  4.333333   2  2.333333

In [175]:
pt.reset_index()

   구분  크기  금액                      수량
          max      mean min      mean
0  가전  대형   9  7.500000   6  5.500000
1  가전  소형   9  8.500000   8  5.500000
2  전자  대형   5  4.500000   4  2.000000
3  전자  소형   6  4.333333   2  2.333333

## Section21.Quiz

In [176]:
# 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "메뉴":['아메리카노', '카페라떼', '에스프레소', '카페모카', '바닐라라떼'],
    "가격":[4500, 5000, 4000, 5900, 5300],
    "칼로리":[10, 110, np.NaN, 210, np.NaN],
    "원산지":['과테말라','브라질','과테말라', np.NaN, np.NaN]
})
df

AttributeError: `np.NaN` was removed in the NumPy 2.0 release. Use `np.nan` instead.

**1. '칼로리' 컬럼 결측치는 칼로리 데이터 중 최소값으로 결측치를 채우시오**

In [ ]:
min_cal = df['칼로리'].min()
df['칼로리'] = df['칼로리'].fillna(min_cal)
df

**2. '원산지' 컬럼 결측치는 원두 데이터 중 최빈값으로 결측치를 채우시오**

In [ ]:
f = df['원산지'].mode()[0]
df['원산지'] = df['원산지'].fillna(f)
df

**3. 가격이 5000 이상인 데이터의 수를 구하시오**

In [ ]:
cond = df['가격'] >= 5000
len(df[cond]) # 또는 sum(cond)

**4. ’이벤트가’ 컬럼을 만들고 기존 가격에서 50% 할인된 가격을 채우시오**

In [ ]:
df['이벤트가'] = df['가격'] * 0.5
df

**5. '칼로리' 컬럼을 삭제하시오**
-

In [ ]:
df = df.drop('칼로리', axis=1)
df

**6. 앞에서부터 3개의 데이터만 선택하시오(loc 활용)**

In [ ]:
df.loc[:2]

**7. 앞에서부터 3개의 데이터만 선택하시오(iloc 활용)**

In [ ]:
df.iloc[:3]

**8. 주어진 데이터(df)에서 아래 값을 loc를 활용해 데이터 프레임으로 출력하시오**
- 카페라떼	5000
- 에스프레소 4000

In [ ]:
# loc
df.loc[1:2, :'가격']

**9. 주어진 데이터(df)에서 아래 값을 iloc를 활용해 데이터 프레임으로 출력하시오**
- 카페라떼	5000
- 에스프레소 4000

In [ ]:
# iloc
df.iloc[1:3, :2]

**10. 메뉴 중 가격이 가장 비싼 순으로 정렬해 상위 3개 값을 구하시오**

In [ ]:
df = df.sort_values('가격', ascending=False)
df.iloc[:3]